DELETE FROM usuarios WHERE NOMBRE_USUARIO='Pepito';
select * from usuarios;
select * from carrito;
SELECT * FROM CARRITO WHERE NOMBRE_USUARIO='Pepito';
DELETE FROM Carrito WHERE NOMBRE_USUARIO='Pepito' AND ID_ARTICULO=2;

SELECT * FROM Carrito WHERE NOMBRE_USUARIO='Pepito' AND ID_ARTICULO=5 AND ID=(SELECT MIN(ID) FROM Carrito WHERE NOMBRE_USUARIO='Pepito' AND ID_ARTICULO=5);

SELECT * FROM USUARIOS;
SELECT * FROM ROLES;